apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-app
  labels:
    app: college-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: college-app
  template:
    metadata:
      labels:
        app: college-app
    spec:
      containers:
      - name: college-app
        image: 377977679082.dkr.ecr.ap-south-1.amazonaws.com/python/college:1.0
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
