# Generated by Django 4.0.5 on 2022-07-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_addadtimisionenquire_table_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_visiter_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('visitorname', models.CharField(max_length=100)),
                ('visitedfor', models.CharField(max_length=100)),
                ('timein', models.CharField(max_length=100)),
                ('timeout', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='addadtimisionenquire_table',
            name='profile_pic',
        ),
    ]
