# Generated by Django 4.0.5 on 2022-07-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_add_visiter_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_studentadmission_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceno', models.CharField(max_length=100)),
                ('studentname', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
            ],
        ),
    ]
