# Generated by Django 4.0.5 on 2022-07-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_add_studentadmission_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_studentadmission_table',
            old_name='referenceno',
            new_name='reference',
        ),
    ]
